name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set bot token
      run: echo "${{ secrets.BOT_TOKEN }}"" > bot_token.txt

    - name: Set Cobalt Session
      run: echo "${{ secrets.COBALT_SESSION }}"" > session.txt
      
    - name: Set characters
      run: echo "${{ secrets.CHARACTERS }}" > characters.txt
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dnd-beyond-bot:latest
